# Generated by Django 3.2.5 on 2021-07-30 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('number_of_lessons', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Class_Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='picket.kelas')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='picket.student')),
            ],
        ),
    ]


# Use Command + P to search for 'settings.py'
# Step 1: Go into settings.py and add the following line:
# 'picket.apps.PicketConfig' or 'picket' to the INSTALLED_APPS list.

# Step 2: Run the following command:
# python manage.py makemigrations
# this will automatically create the migration files, looks like '0002_initial.py'

# Step 3: Run the following command:
# python manage.py migrate
# this will apply the migration files to the database

# Step 4: No step 4. You're done. Check the database to make sure the new data is there.   